### ISSUE TITLE
InstanceSegmentation import of data_augmentation

### ISSUE THREAD

**Issue by NabJa** [marrlab/InstantDL#2]
I get a `ModuleNotFoundError: No module named 'data_generator'` when running `RCNNmodel.load_image_gt`.

Import is done as [(here)](https://github.com/marrlab/InstantDL/blob/master/instantdl/segmentation/RCNNmodel.py#L1247):
`from data_generator.data_augmentation import data_augentation`

Shouldn't it be:
`from instantdl.data_generator.data_augmentation import data_augentation` ?

**Comment by aliechoes** [comment]
thanks for finding it. It is correct. Feel free to open a pull request for changes
