### ISSUE TITLE
GetPipeline error

### ISSUE THREAD

**Issue by DLMLDW** [marrlab/InstantDL#23]
When I run InstantDL with: 

from instantdl import GetPipeLine

configs = {"use_algorithm": "SemanticSegmentation","path": "/home/dominik/Documents/InstantDL_dev_lsd/Vessel12_small2/","batchsize": 1,"iterations_over_dataset": 10,"data_gen_args": {},"loss_function": "mse"}

pipeline = GetPipeLine(configs)

I get the following error: 
TypeError: GetPipeLine() missing 10 required positional arguments: 'path', 'pretrained_weights', 'batchsize', 'iterations_over_dataset', 'data_gen_args', 'loss_function', 'num_classes', 'image_size', 'calculate_uncertainty', and 'evaluation'

Running it in PyCharm is no problem at all

**Comment by aliechoes** [comment]
on which branch? develop or master? Also, is it the latest version?

**Comment by DLMLDW** [comment]
I got it on the latest version of develop. Can you reproduce it?

**Comment by aliechoes** [comment]
I think I have a hunch about the error. Is instantdl installed on your conda as well?
