### ISSUE TITLE
Missing data organization figure

### ISSUE THREAD

**Issue by AhmadQasim** [marrlab/InstantDL#31]
In the README file at: https://github.com/marrlab/InstantDL/tree/develop/instantdl#how-to-use-the-code, the following sentence: 

"The pipeline is based on folders. Please put your data manually in the corresponding folders as illustrated by the figure above. The folder names must not be changed as this will stop the pipeline from functioning.", says that the data organization can be viewed using a figure. The figure is not found in the README.

**Comment by DLMLDW** [comment]
Solved on the develop branch
